/** One stop on an itinerary. May lack coordinates (typed manually, not yet geocoded). */
export interface Stop {
  id: string
  name: string
  lat?: number
  lng?: number
  time?: string        // 'HH:MM' local clock label, optional
  durationMin?: number
  note?: string
  category?: string     // e.g. 'museum', 'food' — supplied by geocoding/agent, display-only
}

export interface Day {
  id: string
  label: string         // e.g. 'Day 1'
  date?: string         // ISO 'YYYY-MM-DD', optional
  stops: Stop[]
}

export interface Trip {
  id: string
  title: string
  destination?: string  // region for the whole trip, e.g. 'Kauai, Hawaii' — scopes stop geocoding
  mapsEnabled: boolean  // per-trip online-maps consent (Milestone 2)
  days: Day[]
}

export interface TripState {
  trips: Trip[]
  activeId: string | null
  focusedDayId: string | null   // which day's route the map shows
}

/** Input for adding a stop (id is generated by the store). */
export interface StopInput {
  name: string
  lat?: number
  lng?: number
  time?: string
  durationMin?: number
  note?: string
  category?: string
}

export interface ItineraryDayInput { label: string; date?: string; stops: StopInput[] }

/** A pending agent proposal against the trip module. */
export type TripProposalPayload =
  | { kind: 'add-stops'; tripId: string; dayId: string; stops: StopInput[] }
  | { kind: 'build-itinerary'; title: string; destination?: string; days: ItineraryDayInput[] }
